### ISSUE TITLE
about env file

### ISSUE THREAD

**Issue by the-monk001** [Amirhossein10/file_to_link_Telegram_bot#1]
can you lease explain what is bot id and where can i get it 
i got bot-token from botfather

**Comment by Amirhossein10** [comment]
Hello
Bot id is bot-token from botfather.
And for get api_id and api_hash you should use https://my.telegram.org/ .

**Comment by the-monk001** [comment]
You have BOT_ID BOT_TOKEN and FILES_DIR in the env file

**Comment by Amirhossein10** [comment]
That bot id means bot username

**Comment by the-monk001** [comment]
can we talk on telegram??

**Comment by Amirhossein10** [comment]
Give me your username in Telegram.

**Comment by the-monk001** [comment]
Bot_xd
